# Generated by Django 4.1.5 on 2023-02-25 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_banner_options_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': '1. Banners'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
