# Generated by Django 4.1.5 on 2023-02-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_banner_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isFeatured',
            field=models.BooleanField(default=False),
        ),
    ]
