# Generated by Django 4.1.5 on 2023-02-25 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_isfeatured_product_isfeatured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='isfeatured',
            new_name='is_featured',
        ),
    ]
