# Generated by Django 4.1.5 on 2023-02-25 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_isfeatured_product_is_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='title',
            new_name='img',
        ),
    ]
