# Generated by Django 4.1.5 on 2023-02-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_banner_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.ImageField(upload_to='media/banner_images/'),
        ),
    ]
